window.SortVisualizerQuizData = [
  {
    id: "bubble-basic-compare",
    algorithm: "bubble",
    algorithmName: "Bubble Sort",
    question: "Bubble Sort 每一輪主要透過哪一種操作推進排序？",
    options: ["比較相鄰元素並在需要時交換", "每次直接找到全域最大值", "把元素分成左右兩半遞迴排序", "使用額外佇列保存所有元素"],
    answer: "比較相鄰元素並在需要時交換",
    explanation: "Bubble Sort 的核心是反覆比較相鄰兩個元素，順序錯誤時交換，因此較大的值會逐步移到右側。",
  },
  {
    id: "bubble-stability",
    algorithm: "bubble",
    algorithmName: "Bubble Sort",
    question: "在標準實作中，Bubble Sort 通常具備哪個特性？",
    options: ["穩定排序", "一定需要 O(n) 額外空間", "平均時間複雜度是 O(log n)", "只適合已排序資料，其他情況無法使用"],
    answer: "穩定排序",
    explanation: "標準 Bubble Sort 只在左邊元素大於右邊元素時交換，相等元素不會互換，因此通常是穩定排序。",
  },
  {
    id: "selection-min",
    algorithm: "selection",
    algorithmName: "Selection Sort",
    question: "Selection Sort 的每一輪通常會做什麼？",
    options: ["找出未排序區間的最小值並放到前面", "只比較相鄰兩個元素", "建立一棵二元搜尋樹", "把資料切成固定大小的桶子"],
    answer: "找出未排序區間的最小值並放到前面",
    explanation: "Selection Sort 會在未排序區間尋找最小值，再與目前位置交換，逐步擴大已排序區間。",
  },
  {
    id: "selection-swaps",
    algorithm: "selection",
    algorithmName: "Selection Sort",
    question: "相較於 Bubble Sort，Selection Sort 的一個常見特色是什麼？",
    options: ["交換次數通常較少", "永遠是穩定排序", "最佳情況時間複雜度是 O(1)", "必須使用遞迴"],
    answer: "交換次數通常較少",
    explanation: "Selection Sort 每一輪最多交換一次，因此交換次數通常少於 Bubble Sort，但比較次數仍是 O(n²)。",
  },
  {
    id: "insertion-hand",
    algorithm: "insertion",
    algorithmName: "Insertion Sort",
    question: "Insertion Sort 最常被比喻成哪一種日常動作？",
    options: ["整理手牌", "洗牌", "排隊抽號碼牌", "翻字典查單字"],
    answer: "整理手牌",
    explanation: "Insertion Sort 會把目前元素插入前方已排序區間，過程很像一張一張整理手牌。",
  },
  {
    id: "insertion-nearly-sorted",
    algorithm: "insertion",
    algorithmName: "Insertion Sort",
    question: "Insertion Sort 特別適合哪一類資料？",
    options: ["接近排序完成的小型資料", "完全隨機且超大型資料", "只能包含負數的資料", "不能有重複值的資料"],
    answer: "接近排序完成的小型資料",
    explanation: "當資料幾乎已排序時，Insertion Sort 需要移動的元素較少，表現可以接近 O(n)。",
  },
  {
    id: "quick-pivot",
    algorithm: "quick",
    algorithmName: "Quick Sort",
    question: "Quick Sort 的 partition 步驟主要目標是什麼？",
    options: ["依 pivot 把資料分成較小與較大的兩側", "每次只交換相鄰元素", "先建立最大堆", "把所有元素複製到佇列中"],
    answer: "依 pivot 把資料分成較小與較大的兩側",
    explanation: "Quick Sort 會選擇 pivot，將比 pivot 小的元素放一側、較大的放另一側，再遞迴排序左右區間。",
  },
  {
    id: "quick-complexity",
    algorithm: "quick",
    algorithmName: "Quick Sort",
    question: "Quick Sort 平均時間複雜度通常是？",
    options: ["O(n log n)", "O(n)", "O(log n)", "O(n³)"],
    answer: "O(n log n)",
    explanation: "在 pivot 分割大致均衡時，Quick Sort 會形成約 log n 層分割，每層處理 n 個元素，因此平均為 O(n log n)。",
  },
  {
    id: "merge-core",
    algorithm: "merge",
    algorithmName: "Merge Sort",
    question: "Merge Sort 的核心策略是什麼？",
    options: ["切半排序後再合併", "每輪找最小值", "把最大值推到陣列尾端", "只處理相鄰反序"],
    answer: "切半排序後再合併",
    explanation: "Merge Sort 是分治法：先將資料切成小區間，排序後再依序合併成完整排序結果。",
  },
  {
    id: "merge-space",
    algorithm: "merge",
    algorithmName: "Merge Sort",
    question: "標準 Merge Sort 通常需要哪種額外成本？",
    options: ["O(n) 額外空間", "O(1) 且一定原地排序", "不需要比較元素", "只能排序已排序資料"],
    answer: "O(n) 額外空間",
    explanation: "標準 Merge Sort 在合併時通常需要暫存陣列，因此空間複雜度常見為 O(n)。",
  },
  {
    id: "heap-structure",
    algorithm: "heap",
    algorithmName: "Heap Sort",
    question: "Heap Sort 排序前通常會先建立哪一種結構？",
    options: ["最大堆", "雜湊表", "環狀佇列", "已排序鍊結串列"],
    answer: "最大堆",
    explanation: "升冪 Heap Sort 會先建立最大堆，讓最大值位於堆頂，接著反覆把最大值移到尾端。",
  },
  {
    id: "heap-stability",
    algorithm: "heap",
    algorithmName: "Heap Sort",
    question: "Heap Sort 的常見特性是哪一項？",
    options: ["可原地排序但通常不穩定", "一定是穩定排序", "平均時間複雜度是 O(n²)", "必須使用 O(n²) 空間"],
    answer: "可原地排序但通常不穩定",
    explanation: "Heap Sort 可以在陣列內完成堆化與交換，額外空間低，但交換過程可能改變相等元素的相對順序。",
  },
];
