window.SortVisualizerQuizData = [
  {
    id: "bubble-basic-compare",
    algorithm: "bubble",
    algorithmName: "Bubble Sort",
    question: "Bubble Sort 每一輪主要透過哪一種操作推進排序？",
    options: ["比較相鄰元素並在需要時交換", "每次直接找到全域最大值", "把元素分成左右兩半遞迴排序", "使用額外佇列保存所有元素"],
    answer: "比較相鄰元素並在需要時交換",
    explanation: "Bubble Sort 的核心是反覆比較相鄰兩個元素，順序錯誤時交換，因此較大的值會逐步移到右側。",
  },
  {
    id: "bubble-stability",
    algorithm: "bubble",
    algorithmName: "Bubble Sort",
    question: "在標準實作中，Bubble Sort 通常具備哪個特性？",
    options: ["穩定排序", "一定需要 O(n) 額外空間", "平均時間複雜度是 O(log n)", "只適合已排序資料，其他情況無法使用"],
    answer: "穩定排序",
    explanation: "標準 Bubble Sort 只在左邊元素大於右邊元素時交換，相等元素不會互換，因此通常是穩定排序。",
  },
  {
    id: "selection-min",
    algorithm: "selection",
    algorithmName: "Selection Sort",
    question: "Selection Sort 的每一輪通常會做什麼？",
    options: ["找出未排序區間的最小值並放到前面", "只比較相鄰兩個元素", "建立一棵二元搜尋樹", "把資料切成固定大小的桶子"],
    answer: "找出未排序區間的最小值並放到前面",
    explanation: "Selection Sort 會在未排序區間尋找最小值，再與目前位置交換，逐步擴大已排序區間。",
  },
  {
    id: "selection-swaps",
    algorithm: "selection",
    algorithmName: "Selection Sort",
    question: "相較於 Bubble Sort，Selection Sort 的一個常見特色是什麼？",
    options: ["交換次數通常較少", "永遠是穩定排序", "最佳情況時間複雜度是 O(1)", "必須使用遞迴"],
    answer: "交換次數通常較少",
    explanation: "Selection Sort 每一輪最多交換一次，因此交換次數通常少於 Bubble Sort，但比較次數仍是 O(n²)。",
  },
  {
    id: "insertion-hand",
    algorithm: "insertion",
    algorithmName: "Insertion Sort",
    question: "Insertion Sort 最常被比喻成哪一種日常動作？",
    options: ["整理手牌", "洗牌", "排隊抽號碼牌", "翻字典查單字"],
    answer: "整理手牌",
    explanation: "Insertion Sort 會把目前元素插入前方已排序區間，過程很像一張一張整理手牌。",
  },
  {
    id: "insertion-nearly-sorted",
    algorithm: "insertion",
    algorithmName: "Insertion Sort",
    question: "Insertion Sort 特別適合哪一類資料？",
    options: ["接近排序完成的小型資料", "完全隨機且超大型資料", "只能包含負數的資料", "不能有重複值的資料"],
    answer: "接近排序完成的小型資料",
    explanation: "當資料幾乎已排序時，Insertion Sort 需要移動的元素較少，表現可以接近 O(n)。",
  },
];
